In [29]:
import pandas as pd

df_results_hdbscan = pd.read_csv("../data/bertopic_parameter_tuning_results_sample_3.csv")
df_results_kmeans = pd.read_csv("../data/bertopic_parameter_tuning_results_sample_kmeans.csv")
data_frame = pd.read_csv("../data/df_clean_text.csv",engine = 'python', on_bad_lines='skip')

In [34]:
# merge dos resultados com k-means e hdbscan
df_results_hdbscan['clusterizacao'] = 'HDBSCAN'
df_results_kmeans['clusterizacao'] = 'K-means'

df_results = pd.concat([df_results_hdbscan, df_results_kmeans], ignore_index=True)

In [35]:
# dropa as linhas que nao usaram neuralmind/bert-base-portuguese-cased ou paraphrase-MiniLM-L6-v2 como modelo de embedding
df_results = df_results[df_results['embedding_model'].isin(['paraphrase-MiniLM-L6-v2', 'neuralmind/bert-base-portuguese-cased'])]

display(df_results)

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score,clusterizacao,n_clusters
2,10,5,0.0,50.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.454341,0.730952,0.593665,0.592986,HDBSCAN,NaN
3,10,5,0.0,50.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.601052,0.720000,0.427699,0.582917,HDBSCAN,NaN
6,10,5,0.0,50.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.458236,0.800000,0.680017,0.646084,HDBSCAN,NaN
7,10,5,0.0,50.0,10.0,0.1,neuralmind/bert-base-portuguese-cased,0.620353,0.765385,0.494254,0.626664,HDBSCAN,NaN
10,10,5,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875000,0.862310,0.737020,HDBSCAN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,20,10,0.5,NaN,NaN,NaN,neuralmind/bert-base-portuguese-cased,0.549001,0.670000,0.218300,0.479100,K-means,20.0
620,20,10,0.5,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.460833,0.691667,0.228615,0.460371,K-means,30.0
621,20,10,0.5,NaN,NaN,NaN,neuralmind/bert-base-portuguese-cased,0.505575,0.748333,0.201579,0.485162,K-means,30.0
622,20,10,0.5,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.452815,0.799000,0.243123,0.498313,K-means,50.0
623,20,10,0.5,NaN,NaN,NaN,neuralmind/bert-base-portuguese-cased,0.000000,0.792000,0.186072,0.326024,K-means,50.0

In [36]:
import os
# Desativa o carregamento de adaptadores desnecessários
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# Opcional: Se você estiver em um ambiente compartilhado, 
# force o cache para uma pasta local onde você tem controle total
local_cache = os.path.join(os.getcwd(), "hf_cache")
os.makedirs(local_cache, exist_ok=True)
os.environ["HF_HOME"] = local_cache

In [37]:
# Calcula a média das métricas
df_results['mean_score'] = df_results[['coherence', 'diversity', 'silhouette']].mean(axis=1)

# 20 melhores por média
top20_mean = df_results.sort_values(by='mean_score', ascending=False).head(20)

# 20 melhores por diversidade, mas ordenados pela média
top20_diversity = (
    df_results.sort_values(by='diversity', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por coerência, mas ordenados pela média
top20_coherence = (
    df_results.sort_values(by='coherence', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por silhueta, mas ordenados pela média
top20_silhouette = (
    df_results.sort_values(by='silhouette', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

best_mean_row = top20_mean
best_coherence_row = top20_coherence
best_silhouette_row = top20_silhouette
best_diversity_row = top20_diversity
# Exibe os resultados
display(best_mean_row)
display(best_coherence_row)
display(best_diversity_row)
display(best_silhouette_row)

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score,clusterizacao,n_clusters
419,20,10,0.5,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.615816,0.887500,0.820250,0.774522,HDBSCAN,NaN
83,10,5,0.5,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.564070,0.933333,0.731759,0.743054,HDBSCAN,NaN
395,20,10,0.1,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.573290,0.966667,0.685602,0.741853,HDBSCAN,NaN
95,10,5,0.5,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.516016,0.950000,0.751812,0.739276,HDBSCAN,NaN
107,10,5,0.5,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.516016,0.950000,0.751812,0.739276,HDBSCAN,NaN
34,10,5,0.0,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875000,0.862310,0.737020,HDBSCAN,NaN
22,10,5,0.0,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875000,0.862310,0.737020,HDBSCAN,NaN
10,10,5,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875000,0.862310,0.737020,HDBSCAN,NaN
431,20,10,0.5,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.533149,0.975000,0.698625,0.735592,HDBSCAN,NaN
496,10,10,0.1,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.369099,1.000000,0.829043,0.732714,K-means,2.0
71,10,5,0.1,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.565809,0.933333,0.697861,0.732334,HDBSCAN,NaN
179,10,10,0.1,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.565809,0.933333,0.696109,0.731750,HDBSCAN,NaN
154,10,10,0.1,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.497644,0.875000,0.816773,0.729806,HDBSCAN,NaN
178,10,10,0.1,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.497644,0.875000,0.816773,0.729806,HDBSCAN,NaN
166,10,10,0.1,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.497644,0.875000,0.816773,0.729806,HDBSCAN,NaN
134,10,10,0.0,150.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.464485,0.875000,0.842508,0.727331,HDBSCAN,NaN
122,10,10,0.0,100.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.464485,0.875000,0.842508,0.727331,HDBSCAN,NaN
18,10,5,0.0,100.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.452636,0.875000,0.852480,0.726705,HDBSCAN,NaN
30,10,5,0.0,150.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.452636,0.875000,0.852480,0.726705,HDBSCAN,NaN
448,10,5,0.1,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.369099,1.000000,0.810708,0.726603,K-means,2.0

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score,clusterizacao,n_clusters
419,20,10,0.5,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.615816,0.887500,0.820250,0.774522,HDBSCAN,NaN
383,20,10,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.641153,0.937500,0.524137,0.700930,HDBSCAN,NaN
59,10,5,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.630194,0.937500,0.523602,0.697099,HDBSCAN,NaN
167,10,10,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.630194,0.937500,0.520106,0.695933,HDBSCAN,NaN
35,10,5,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.623723,0.937500,0.518037,0.693086,HDBSCAN,NaN
143,10,10,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.625622,0.937500,0.511076,0.691399,HDBSCAN,NaN
87,10,5,0.5,100.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.617028,0.941667,0.510733,0.689809,HDBSCAN,NaN
263,20,5,0.1,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.643794,0.728571,0.674767,0.682378,HDBSCAN,NaN
275,20,5,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.662769,0.840000,0.536641,0.679803,HDBSCAN,NaN
359,20,10,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.647147,0.830000,0.495151,0.657433,HDBSCAN,NaN
347,20,10,0.0,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.647147,0.830000,0.495151,0.657433,HDBSCAN,NaN
131,10,10,0.0,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.650895,0.841667,0.472178,0.654913,HDBSCAN,NaN
23,10,5,0.0,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.646866,0.841667,0.472078,0.653537,HDBSCAN,NaN
239,20,5,0.0,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.645370,0.840000,0.474488,0.653286,HDBSCAN,NaN
251,20,5,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.645370,0.840000,0.474488,0.653286,HDBSCAN,NaN
47,10,5,0.1,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.652465,0.785714,0.463421,0.633867,HDBSCAN,NaN
271,20,5,0.1,100.0,10.0,0.1,neuralmind/bert-base-portuguese-cased,0.620447,0.775000,0.499781,0.631743,HDBSCAN,NaN
155,10,10,0.1,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.652900,0.785714,0.443714,0.627443,HDBSCAN,NaN
7,10,5,0.0,50.0,10.0,0.1,neuralmind/bert-base-portuguese-cased,0.620353,0.765385,0.494254,0.626664,HDBSCAN,NaN
371,20,10,0.1,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.641932,0.750000,0.428218,0.606717,HDBSCAN,NaN

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score,clusterizacao,n_clusters
395,20,10,0.1,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.573290,0.966667,0.685602,0.741853,HDBSCAN,NaN
95,10,5,0.5,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.516016,0.950000,0.751812,0.739276,HDBSCAN,NaN
107,10,5,0.5,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.516016,0.950000,0.751812,0.739276,HDBSCAN,NaN
431,20,10,0.5,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.533149,0.975000,0.698625,0.735592,HDBSCAN,NaN
496,10,10,0.1,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.369099,1.000000,0.829043,0.732714,K-means,2.0
448,10,5,0.1,NaN,NaN,NaN,paraphrase-MiniLM-L6-v2,0.369099,1.000000,0.810708,0.726603,K-means,2.0
311,20,5,0.5,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.503374,0.950000,0.711013,0.721462,HDBSCAN,NaN
323,20,5,0.5,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.503374,0.950000,0.711013,0.721462,HDBSCAN,NaN
383,20,10,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.641153,0.937500,0.524137,0.700930,HDBSCAN,NaN
59,10,5,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.630194,0.937500,0.523602,0.697099,HDBSCAN,NaN
167,10,10,0.1,100.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.630194,0.937500,0.520106,0.695933,HDBSCAN,NaN
35,10,5,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.623723,0.937500,0.518037,0.693086,HDBSCAN,NaN
143,10,10,0.0,150.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.625622,0.937500,0.511076,0.691399,HDBSCAN,NaN
87,10,5,0.5,100.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.617028,0.941667,0.510733,0.689809,HDBSCAN,NaN
391,20,10,0.1,150.0,10.0,0.1,neuralmind/bert-base-portuguese-cased,0.561914,0.940000,0.337543,0.613152,HDBSCAN,NaN
207,10,10,0.5,150.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.417850,0.975000,0.347584,0.580145,HDBSCAN,NaN
195,10,10,0.5,100.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.417850,0.975000,0.347584,0.580145,HDBSCAN,NaN
183,10,10,0.5,50.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.450418,0.983333,0.093201,0.508984,HDBSCAN,NaN
407,20,10,0.5,50.0,100.0,0.1,neuralmind/bert-base-portuguese-cased,0.539876,0.950000,-0.054986,0.478297,HDBSCAN,NaN
75,10,5,0.5,50.0,5.0,0.1,neuralmind/bert-base-portuguese-cased,0.421244,0.983333,-0.084239,0.440113,HDBSCAN,NaN

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score,clusterizacao,n_clusters
22,10,5,0.0,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875,0.862310,0.737020,HDBSCAN,NaN
10,10,5,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875,0.862310,0.737020,HDBSCAN,NaN
34,10,5,0.0,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.473751,0.875,0.862310,0.737020,HDBSCAN,NaN
134,10,10,0.0,150.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.464485,0.875,0.842508,0.727331,HDBSCAN,NaN
122,10,10,0.0,100.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.464485,0.875,0.842508,0.727331,HDBSCAN,NaN
30,10,5,0.0,150.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.452636,0.875,0.852480,0.726705,HDBSCAN,NaN
18,10,5,0.0,100.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.452636,0.875,0.852480,0.726705,HDBSCAN,NaN
14,10,5,0.0,100.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.452488,0.875,0.851775,0.726421,HDBSCAN,NaN
26,10,5,0.0,150.0,5.0,0.1,paraphrase-MiniLM-L6-v2,0.452488,0.875,0.851775,0.726421,HDBSCAN,NaN
358,20,10,0.0,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.846822,0.724476,HDBSCAN,NaN
334,20,10,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.846821,0.724476,HDBSCAN,NaN
346,20,10,0.0,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.846821,0.724476,HDBSCAN,NaN
126,10,10,0.0,100.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.843418,0.723341,HDBSCAN,NaN
138,10,10,0.0,150.0,10.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.843418,0.723341,HDBSCAN,NaN
250,20,5,0.0,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.836802,0.721136,HDBSCAN,NaN
226,20,5,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.836802,0.721136,HDBSCAN,NaN
238,20,5,0.0,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.451606,0.875,0.836801,0.721136,HDBSCAN,NaN
118,10,10,0.0,50.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.454369,0.850,0.854451,0.719607,HDBSCAN,NaN
130,10,10,0.0,100.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.454369,0.850,0.854451,0.719607,HDBSCAN,NaN
142,10,10,0.0,150.0,100.0,0.1,paraphrase-MiniLM-L6-v2,0.454369,0.850,0.854451,0.719607,HDBSCAN,NaN

In [38]:
'''Remoção de Stopwords'''
from PreProcessing.pre_processing import PreProcessing
from nltk.corpus import stopwords

pp = PreProcessing(language="pt")

custom_stopwords = [line.strip() for line in open('stopwords.txt', 'r', encoding='utf-8')]
pt_stopwords = set(stopwords.words('portuguese'))
pp.append_stopwords_list(list(pt_stopwords - set(pp.stopwords)) + custom_stopwords)

data_frame["clean_text"] = data_frame["clean_text"].apply(
    lambda t: " ".join(
        [w for w in pp.remove_stopwords(t).split() if len(w) <= 20]
    )
)

In [39]:
import csv

nan_count = data_frame['clean_text'].isna().sum()
df = data_frame[data_frame['clean_text'].notna()].reset_index(drop=True)
print(f"{nan_count} rows with NaN in 'clean_text' were removed.")

duplicate_count = df.duplicated(subset=['clean_text']).sum()
df.drop_duplicates(subset=['clean_text'], inplace=True)
print(f"{duplicate_count} duplicate rows based on 'clean_text' were removed.")

print(f"Total documents after cleaning: {len(df)}")
docs = df['clean_text'].tolist()

print(len(df))
df.to_csv("processed_df.csv", index=False, quoting=csv.QUOTE_ALL)

0 rows with NaN in 'clean_text' were removed.
76 duplicate rows based on 'clean_text' were removed.
Total documents after cleaning: 6394
6394

In [14]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from meu_bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN

default_stopwords = []

def run_bertopic_modeling(docs, n_neighbors, n_components, min_dist, min_cluster_size, min_samples, cluster_eps,embedding_model_name="all-MiniLM-L6-v2"):
    umap_params = {
        "n_neighbors": n_neighbors, 
        "n_components": n_components, 
        "min_dist": min_dist,
        "metric":'cosine',
        "random_state":42
    }

    hdbscan_params = {
        "min_cluster_size": min_cluster_size, 
        "min_samples": min_samples,
        "prediction_data":True,
        "cluster_selection_epsilon": cluster_eps
    }

    bertopic_params = {
        'language': 'portuguese',
        #'verbose': True,
        'top_n_words': 10
    }

    
    embedding_model = SentenceTransformer(
        embedding_model_name, 
        device='cuda', 
        trust_remote_code=True
    )
    vectorizer = TfidfVectorizer(stop_words=default_stopwords,ngram_range=(1, 1))

    umap_model = UMAP(**umap_params)
    hdbscan_model = HDBSCAN(**hdbscan_params)

    model = BERTopic(
        **bertopic_params,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer,
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
    )

    topics, probs = model.fit_transform(docs)
    return model, topics, probs

### Usando CUDA

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from meu_bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer

from cuml.manifold import UMAP
from cuml.cluster import HDBSCAN

default_stopwords = []

def run_bertopic_modeling(docs, n_neighbors, n_components, min_dist, min_cluster_size, min_samples, cluster_eps, embedding_model_name="all-MiniLM-L6-v2"):
    umap_params = {
        "n_neighbors": n_neighbors, 
        "n_components": n_components, 
        "min_dist": min_dist,
        "metric": 'cosine',
        "random_state": 42
    }

    hdbscan_params = {
        "min_cluster_size": min_cluster_size, 
        "min_samples": min_samples,
        "prediction_data": True,
        "cluster_selection_epsilon": cluster_eps
    }

    bertopic_params = {
        'language': 'portuguese',
        #'verbose': True,
        'top_n_words': 10
    }

    embedding_model = SentenceTransformer(
        embedding_model_name, 
        device='cuda', 
        trust_remote_code=True
    )
    
    vectorizer = TfidfVectorizer(stop_words=default_stopwords, ngram_range=(1, 1))

    umap_model = UMAP(**umap_params)
    hdbscan_model = HDBSCAN(**hdbscan_params)

    model = BERTopic(
        **bertopic_params,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer,
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
    )

    topics, probs = model.fit_transform(docs)
    
    if hasattr(topics, "to_numpy"):
        topics = topics.to_numpy().tolist()
    elif hasattr(topics, "get"):
        topics = topics.get().tolist()
    else:
        topics = [int(t) for t in topics]

    return model, topics, probs

### Usando clusterizacao com Kmeans

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from meu_bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer

from cuml.manifold import UMAP
from cuml.cluster import KMeans

default_stopwords = []

def run_bertopic_modeling_kmeans(docs, n_neighbors, n_components, min_dist, n_clusters, embedding_model_name="all-MiniLM-L6-v2"):
    umap_params = {
        "n_neighbors": int(n_neighbors), 
        "n_components": int(n_components), 
        "min_dist": float(min_dist),
        "metric": 'cosine',
        "random_state": 42
    }

    kmeans_params = {
        "n_clusters": int(n_clusters),
        "random_state": 42
    }

    bertopic_params = {
        'language': 'portuguese',
        'top_n_words': 10
    }

    embedding_model = SentenceTransformer(
        embedding_model_name, 
        device='cuda', 
        trust_remote_code=True
    )
    
    vectorizer = TfidfVectorizer(stop_words=default_stopwords, ngram_range=(1, 1))

    umap_model = UMAP(**umap_params)
    kmeans_model = KMeans(**kmeans_params)

    model = BERTopic(
        **bertopic_params,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=kmeans_model, 
        vectorizer_model=vectorizer,
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
    )

    topics, probs = model.fit_transform(docs)
    
    if hasattr(topics, "to_numpy"):
        topics = topics.to_numpy().tolist()
    elif hasattr(topics, "get"):
        topics = topics.get().tolist()
    else:
        topics = [int(t) for t in topics]

    return model, topics, probs

In [49]:
from IPython.display import display

def show_results(model):

    info = model.get_topic_info()
    display(info)

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)
    fig.show()

In [50]:
import os

def save_results(model, dir):
    json_path = os.path.join(dir, "topics.json")
    model.save_json(json_path) 

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)

    barchart_path = os.path.join(dir, "barchart.html")
    fig.write_html(barchart_path) 

    model_path = os.path.join(dir, "bertopic_model")
    model.save(model_path)

    topics_info = model.get_topic_info()
    csv_path = os.path.join(dir, "topics_info.csv")
    topics_info.to_csv(csv_path, index=False)
    
    print(f"Modelo e resultados salvos no diretório '{dir}' (gráfico salvo como HTML)")

In [51]:
for i,row in enumerate(best_mean_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)

    if(row.clusterizacao == 'HDBSCAN'):
        model, topics, probs = run_bertopic_modeling(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist=row.min_dist,
            min_cluster_size=row.min_cluster_size,
            min_samples=row.min_samples,
            cluster_eps=row.cluster_eps,
            embedding_model_name=row.embedding_model 
        )
    else:
        model, topics, probs = run_bertopic_modeling_kmeans(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist = row.min_dist,
            embedding_model_name= row.embedding_model, 
            n_clusters= row.n_clusters
        )
    dir = f"best_mean/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=419, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6158159355503454, diversity=0.8875, silhouette=0.8202499151229858, mean_score=0.7745219502244437, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 26221.81it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:08:20,259 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=83, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5640701654860796, diversity=0.9333333333333332, silhouette=0.7317591309547424, mean_score=0.7430542099247184, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28244.95it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:09:43,858 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=395, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5732904931939408, diversity=0.9666666666666668, silhouette=0.6856018304824829, mean_score=0.7418529967810302, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 15760.62it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:11:04,731 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=95, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5160161234727567, diversity=0.95, silhouette=0.7518115639686584, mean_score=0.739275895813805, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28031.52it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:12:25,757 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=107, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5160161234727567, diversity=0.95, silhouette=0.7518115639686584, mean_score=0.739275895813805, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 42463.70it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:13:58,152 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=34, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10188.51it/s]
2026-06-09 00:14:11,541 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=22, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9412.88it/s]
2026-06-09 00:14:24,884 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=10, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7505.83it/s]
2026-06-09 00:14:37,981 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=431, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5331491722817466, diversity=0.975, silhouette=0.6986254453659058, mean_score=0.7355915392158842, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 27825.00it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:15:58,460 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=496, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=nan, min_samples=nan, cluster_eps=nan, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.3690992631307939, diversity=1.0, silhouette=0.8290428519248962, mean_score=0.7327140383518967, clusterizacao='K-means', n_clusters=2.0)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9647.03it/s]
2026-06-09 00:16:13,861 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=71, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5658088430438322, diversity=0.9333333333333332, silhouette=0.6978610157966614, mean_score=0.7323343973912756, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28586.43it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:17:36,254 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=179, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5658088430438322, diversity=0.9333333333333332, silhouette=0.6961090564727783, mean_score=0.7317504109499812, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 34639.21it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:19:01,486 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=154, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4976442736358575, diversity=0.875, silhouette=0.816772997379303, mean_score=0.7298057570050535, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9108.82it/s]
2026-06-09 00:19:16,965 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=178, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4976442736358575, diversity=0.875, silhouette=0.8167729377746582, mean_score=0.7298057371368385, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11276.78it/s]
2026-06-09 00:19:31,946 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=166, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4976442736358575, diversity=0.875, silhouette=0.8167729377746582, mean_score=0.7298057371368385, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8953.27it/s]
2026-06-09 00:19:47,040 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=134, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.464484693102688, diversity=0.875, silhouette=0.8425078392028809, mean_score=0.7273308441018562, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9573.91it/s]
2026-06-09 00:20:02,196 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=122, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.464484693102688, diversity=0.875, silhouette=0.8425078392028809, mean_score=0.7273308441018562, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9489.17it/s]
2026-06-09 00:20:17,298 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=18, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4526364056474196, diversity=0.875, silhouette=0.8524798154830933, mean_score=0.7267054070435043, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8787.01it/s]
2026-06-09 00:20:31,947 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=30, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4526364056474196, diversity=0.875, silhouette=0.8524798154830933, mean_score=0.7267054070435043, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10582.60it/s]
2026-06-09 00:20:45,463 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=448, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=nan, min_samples=nan, cluster_eps=nan, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.3690992631307939, diversity=1.0, silhouette=0.8107083439826965, mean_score=0.7266025357044968, clusterizacao='K-means', n_clusters=2.0)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9250.82it/s]
2026-06-09 00:21:00,612 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/19' (gráfico salvo como HTML)

In [52]:
for i,row in enumerate(best_coherence_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    if(row.clusterizacao == 'HDBSCAN'):
        model, topics, probs = run_bertopic_modeling(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist=row.min_dist,
            min_cluster_size=row.min_cluster_size,
            min_samples=row.min_samples,
            cluster_eps=row.cluster_eps,
            embedding_model_name=row.embedding_model 
        )
    else:
        model, topics, probs = run_bertopic_modeling_kmeans(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist = row.min_dist,
            embedding_model_name= row.embedding_model, 
            n_clusters= row.n_clusters
        )
    dir = f"best_coherence/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=419, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6158159355503454, diversity=0.8875, silhouette=0.8202499151229858, mean_score=0.7745219502244437, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28931.25it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:24:12,023 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=383, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6411530741820286, diversity=0.9375, silhouette=0.5241366028785706, mean_score=0.7009298923535331, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 29452.93it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:25:27,834 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=59, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6301935486540551, diversity=0.9375, silhouette=0.5236020088195801, mean_score=0.6970985191578783, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 27639.79it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:26:43,161 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=167, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6301935486540551, diversity=0.9375, silhouette=0.5201063752174377, mean_score=0.6959333079571642, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 43321.04it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:28:00,134 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=35, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6237226904841485, diversity=0.9375, silhouette=0.5180367231369019, mean_score=0.6930864712070167, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 36925.61it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:29:18,452 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=143, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6256218159309151, diversity=0.9375, silhouette=0.5110755562782288, mean_score=0.6913991240697146, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 41722.89it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:30:35,593 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=87, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6170276134477222, diversity=0.9416666666666668, silhouette=0.5107326507568359, mean_score=0.689808976957075, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 48224.32it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:31:50,773 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=263, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.643794300394716, diversity=0.7285714285714285, silhouette=0.6747674345970154, mean_score=0.68237772118772, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 36837.61it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:33:04,683 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=275, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6627686662165223, diversity=0.84, silhouette=0.5366412401199341, mean_score=0.6798033021121522, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 41336.49it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:34:19,125 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=359, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6471467657801458, diversity=0.83, silhouette=0.4951512813568115, mean_score=0.6574326823789858, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49414.87it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:35:42,144 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=347, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6471467657801458, diversity=0.83, silhouette=0.4951512217521667, mean_score=0.6574326625107708, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 40093.50it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:37:03,275 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=131, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.650894683958901, diversity=0.8416666666666667, silhouette=0.4721777439117431, mean_score=0.654913031512437, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 32106.26it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:38:15,598 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=23, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.646865725432927, diversity=0.8416666666666667, silhouette=0.4720775485038757, mean_score=0.6535366468678231, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 45041.63it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:39:18,935 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=239, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6453702206508766, diversity=0.84, silhouette=0.4744884967803955, mean_score=0.6532862391437574, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 51128.12it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:40:22,126 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=251, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6453702206508766, diversity=0.84, silhouette=0.4744884967803955, mean_score=0.6532862391437574, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49703.24it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:41:25,694 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=47, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6524652693979353, diversity=0.7857142857142857, silhouette=0.4634206891059875, mean_score=0.6338667480727361, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 42388.22it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:42:29,001 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=271, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100.0, min_samples=10.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.620446515379732, diversity=0.775, silhouette=0.4997813403606415, mean_score=0.6317426185801245, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 29433.19it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:43:32,088 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=155, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6529004052526357, diversity=0.7857142857142857, silhouette=0.443714290857315, mean_score=0.6274429939414121, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49245.77it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:44:35,089 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=7, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=50.0, min_samples=10.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6203529024867365, diversity=0.7653846153846153, silhouette=0.4942544996738434, mean_score=0.6266640058483984, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49239.96it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:45:38,312 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=371, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6419322788807261, diversity=0.75, silhouette=0.4282181859016418, mean_score=0.6067168215941227, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 53648.70it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:46:41,932 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/19' (gráfico salvo como HTML)

In [53]:
for i,row in enumerate(best_diversity_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    if(row.clusterizacao == 'HDBSCAN'):
        model, topics, probs = run_bertopic_modeling(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist=row.min_dist,
            min_cluster_size=row.min_cluster_size,
            min_samples=row.min_samples,
            cluster_eps=row.cluster_eps,
            embedding_model_name=row.embedding_model 
        )
    else:
        model, topics, probs = run_bertopic_modeling_kmeans(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist = row.min_dist,
            embedding_model_name= row.embedding_model, 
            n_clusters= row.n_clusters
        )
    dir = f"best_diversity/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=395, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5732904931939408, diversity=0.9666666666666668, silhouette=0.6856018304824829, mean_score=0.7418529967810302, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49034.57it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:47:45,626 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=95, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5160161234727567, diversity=0.95, silhouette=0.7518115639686584, mean_score=0.739275895813805, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 47955.56it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:48:48,990 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=107, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5160161234727567, diversity=0.95, silhouette=0.7518115639686584, mean_score=0.739275895813805, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 46859.79it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:49:51,357 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=431, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5331491722817466, diversity=0.975, silhouette=0.6986254453659058, mean_score=0.7355915392158842, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 45293.38it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:50:54,536 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=496, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=nan, min_samples=nan, cluster_eps=nan, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.3690992631307939, diversity=1.0, silhouette=0.8290428519248962, mean_score=0.7327140383518967, clusterizacao='K-means', n_clusters=2.0)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13548.68it/s]
2026-06-09 00:51:07,471 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=448, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=nan, min_samples=nan, cluster_eps=nan, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.3690992631307939, diversity=1.0, silhouette=0.8107083439826965, mean_score=0.7266025357044968, clusterizacao='K-means', n_clusters=2.0)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12279.73it/s]
2026-06-09 00:51:20,143 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=311, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5033736375078074, diversity=0.95, silhouette=0.7110125422477722, mean_score=0.7214620599185265, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 29075.36it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:52:22,043 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=323, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5033736375078074, diversity=0.95, silhouette=0.7110125422477722, mean_score=0.7214620599185265, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 47174.96it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:53:25,494 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=383, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6411530741820286, diversity=0.9375, silhouette=0.5241366028785706, mean_score=0.7009298923535331, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 52617.19it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:54:28,616 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=59, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6301935486540551, diversity=0.9375, silhouette=0.5236020088195801, mean_score=0.6970985191578783, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 50484.88it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:55:35,692 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=167, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6301935486540551, diversity=0.9375, silhouette=0.5201063752174377, mean_score=0.6959333079571642, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 54926.72it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:56:39,655 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=35, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6237226904841485, diversity=0.9375, silhouette=0.5180367231369019, mean_score=0.6930864712070167, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49000.03it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:57:43,246 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=143, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6256218159309151, diversity=0.9375, silhouette=0.5110755562782288, mean_score=0.6913991240697146, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 44293.49it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:58:46,983 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=87, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6170276134477222, diversity=0.9416666666666668, silhouette=0.5107326507568359, mean_score=0.689808976957075, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 47831.89it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 00:59:51,964 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=391, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150.0, min_samples=10.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5619139122116867, diversity=0.94, silhouette=0.3375433087348938, mean_score=0.6131524069821935, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 51823.33it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:00:56,004 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=207, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=150.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4178495011535744, diversity=0.975, silhouette=0.3475842177867889, mean_score=0.5801445729801211, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 40271.47it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:01:59,836 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=195, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4178495011535744, diversity=0.975, silhouette=0.3475842177867889, mean_score=0.5801445729801211, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49576.29it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:03:04,041 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=183, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4504183161601058, diversity=0.9833333333333332, silhouette=0.0932010039687156, mean_score=0.5089842178207182, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 30109.54it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:04:08,025 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=407, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5398760280417054, diversity=0.95, silhouette=-0.0549859963357448, mean_score=0.47829667723532016, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 49017.29it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:05:11,999 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=75, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=50.0, min_samples=5.0, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4212435443986453, diversity=0.9833333333333332, silhouette=-0.0842391774058342, mean_score=0.4401125667753814, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 48876.65it/s]
[transformers] BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-09 01:06:15,576 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/19' (gráfico salvo como HTML)

In [54]:
for i,row in enumerate(best_silhouette_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    if(row.clusterizacao == 'HDBSCAN'):
        model, topics, probs = run_bertopic_modeling(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist=row.min_dist,
            min_cluster_size=row.min_cluster_size,
            min_samples=row.min_samples,
            cluster_eps=row.cluster_eps,
            embedding_model_name=row.embedding_model 
        )
    else:
        model, topics, probs = run_bertopic_modeling_kmeans(
            docs=docs,
            n_neighbors=row.n_neighbors,
            n_components=row.n_components,
            min_dist = row.min_dist,
            embedding_model_name= row.embedding_model, 
            n_clusters= row.n_clusters
        )
    dir = f"best_silhouette/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=22, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11387.35it/s]
2026-06-09 01:06:28,261 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=10, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13206.57it/s]
2026-06-09 01:06:41,455 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=34, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4737512001891553, diversity=0.875, silhouette=0.8623101711273193, mean_score=0.7370204571054915, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9688.57it/s]
2026-06-09 01:06:53,121 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=134, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.464484693102688, diversity=0.875, silhouette=0.8425078392028809, mean_score=0.7273308441018562, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12479.44it/s]
2026-06-09 01:07:06,036 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=122, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.464484693102688, diversity=0.875, silhouette=0.8425078392028809, mean_score=0.7273308441018562, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12566.20it/s]
2026-06-09 01:07:18,088 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=30, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4526364056474196, diversity=0.875, silhouette=0.8524798154830933, mean_score=0.7267054070435043, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12193.78it/s]
2026-06-09 01:07:31,357 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=18, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4526364056474196, diversity=0.875, silhouette=0.8524798154830933, mean_score=0.7267054070435043, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12171.79it/s]
2026-06-09 01:07:44,386 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=14, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4524884979798702, diversity=0.875, silhouette=0.8517754673957825, mean_score=0.7264213217918843, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11507.77it/s]
2026-06-09 01:07:58,099 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=26, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=5.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4524884979798702, diversity=0.875, silhouette=0.8517754673957825, mean_score=0.7264213217918843, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11949.91it/s]
2026-06-09 01:08:11,321 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=358, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8468216061592102, mean_score=0.7244757898683325, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11208.61it/s]
2026-06-09 01:08:23,971 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=334, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8468214869499207, mean_score=0.7244757501319027, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11291.51it/s]
2026-06-09 01:08:37,941 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=346, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8468214273452759, mean_score=0.7244757302636877, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10832.02it/s]
2026-06-09 01:08:50,608 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=126, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8434184789657593, mean_score=0.7233414141371822, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11610.76it/s]
2026-06-09 01:09:04,394 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=138, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=10.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8434184193611145, mean_score=0.7233413942689673, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11666.58it/s]
2026-06-09 01:09:17,507 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=250, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8368015289306641, mean_score=0.7211357641254837, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11086.93it/s]
2026-06-09 01:09:32,381 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=226, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8368015289306641, mean_score=0.7211357641254837, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12926.40it/s]
2026-06-09 01:09:45,829 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=238, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4516057634457874, diversity=0.875, silhouette=0.8368014693260193, mean_score=0.7211357442572689, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12397.79it/s]
2026-06-09 01:09:58,592 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=118, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=50.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.454368672340346, diversity=0.85, silhouette=0.854451060295105, mean_score=0.7196065775451504, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12534.48it/s]
2026-06-09 01:10:11,904 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=130, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.454368672340346, diversity=0.85, silhouette=0.854451060295105, mean_score=0.7196065775451504, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12883.23it/s]
2026-06-09 01:10:25,206 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=142, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150.0, min_samples=100.0, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.454368672340346, diversity=0.85, silhouette=0.854451060295105, mean_score=0.7196065775451504, clusterizacao='HDBSCAN', n_clusters=nan)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11274.13it/s]
2026-06-09 01:10:38,668 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/19' (gráfico salvo como HTML)