In [1]:
import pandas as pd

df_results = pd.read_csv("../data/bertopic_parameter_tuning_results_KMeans.csv")
data_frame = pd.read_csv("../data/df_clean_text.csv",engine = 'python', on_bad_lines='skip')

In [2]:
import os
# Desativa o carregamento de adaptadores desnecessários
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# Opcional: Se você estiver em um ambiente compartilhado, 
# force o cache para uma pasta local onde você tem controle total
local_cache = os.path.join(os.getcwd(), "hf_cache")
os.makedirs(local_cache, exist_ok=True)
os.environ["HF_HOME"] = local_cache

In [3]:
# Calcula a média das métricas
df_results['mean_score'] = df_results[['coherence', 'diversity', 'silhouette']].mean(axis=1)

# 20 melhores por média
top20_mean = df_results.sort_values(by='mean_score', ascending=False).head(20)

# 20 melhores por diversidade, mas ordenados pela média
top20_diversity = (
    df_results.sort_values(by='diversity', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por coerência, mas ordenados pela média
top20_coherence = (
    df_results.sort_values(by='coherence', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por silhueta, mas ordenados pela média
top20_silhouette = (
    df_results.sort_values(by='silhouette', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

best_mean_row = top20_mean
best_coherence_row = top20_coherence
best_silhouette_row = top20_silhouette
best_diversity_row = top20_diversity
# Exibe os resultados
display(best_mean_row)
display(best_coherence_row)
display(best_diversity_row)
display(best_silhouette_row)

,n_neighbors,n_components,min_dist,n_clusters,embedding_model,coherence,diversity,silhouette,mean_score
16,10,5,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446978,0.875,0.145923,0.489300
64,10,10,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.442376,0.875,0.142084,0.486487
96,20,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.139562,0.485973
144,20,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.138255,0.485537
0,10,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.137112,0.485156
33,10,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.453815,0.875,0.125731,0.484849
48,10,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.438340,0.875,0.135387,0.482909
129,20,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.125220,0.482355
81,10,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.124755,0.482200
177,20,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.123868,0.481905
160,20,10,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446172,0.850,0.146559,0.480910
112,20,5,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446172,0.850,0.146139,0.480770
32,10,5,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.147500,0.479047
128,20,5,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.146542,0.478727
161,20,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.115341,0.478588
176,20,10,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.145702,0.478447
113,20,5,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.114667,0.478363
80,10,10,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.145096,0.478245
65,10,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.110759,0.477060
17,10,5,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.110497,0.476973

,n_neighbors,n_components,min_dist,n_clusters,embedding_model,coherence,diversity,silhouette,mean_score
85,10,10,0.5,4,neuralmind/bert-base-portuguese-cased,0.540062,0.775000,0.039333,0.451465
15,10,5,0.0,50,neuralmind/bert-base-portuguese-cased,0.557900,0.832000,-0.068309,0.440530
63,10,10,0.0,50,neuralmind/bert-base-portuguese-cased,0.548303,0.826000,-0.068375,0.435310
29,10,5,0.1,30,neuralmind/bert-base-portuguese-cased,0.552489,0.760000,-0.059525,0.417655
11,10,5,0.0,20,neuralmind/bert-base-portuguese-cased,0.545672,0.752500,-0.052028,0.415381
27,10,5,0.1,20,neuralmind/bert-base-portuguese-cased,0.530785,0.752500,-0.041551,0.413911
139,20,5,0.5,20,neuralmind/bert-base-portuguese-cased,0.577662,0.700000,-0.046678,0.410328
73,10,10,0.1,10,neuralmind/bert-base-portuguese-cased,0.556167,0.705000,-0.034752,0.408805
75,10,10,0.1,20,neuralmind/bert-base-portuguese-cased,0.532516,0.747500,-0.054022,0.408665
171,20,10,0.1,20,neuralmind/bert-base-portuguese-cased,0.538401,0.732500,-0.048860,0.407347
125,20,5,0.1,30,neuralmind/bert-base-portuguese-cased,0.532307,0.745000,-0.057120,0.406729
109,20,5,0.0,30,neuralmind/bert-base-portuguese-cased,0.532609,0.743333,-0.058680,0.405754
189,20,10,0.5,30,neuralmind/bert-base-portuguese-cased,0.543188,0.720000,-0.053534,0.403218
91,10,10,0.5,20,neuralmind/bert-base-portuguese-cased,0.561362,0.685000,-0.050264,0.398699
123,20,5,0.1,20,neuralmind/bert-base-portuguese-cased,0.560863,0.675000,-0.056172,0.393231
169,20,10,0.1,10,neuralmind/bert-base-portuguese-cased,0.533597,0.680000,-0.044968,0.389543
185,20,10,0.5,10,neuralmind/bert-base-portuguese-cased,0.539127,0.665000,-0.045959,0.386056
155,20,10,0.0,20,neuralmind/bert-base-portuguese-cased,0.539015,0.667500,-0.053094,0.384473
41,10,5,0.5,10,neuralmind/bert-base-portuguese-cased,0.535317,0.670000,-0.052881,0.384145
89,10,10,0.5,10,neuralmind/bert-base-portuguese-cased,0.538341,0.665000,-0.064854,0.379496

,n_neighbors,n_components,min_dist,n_clusters,embedding_model,coherence,diversity,silhouette,mean_score
16,10,5,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446978,0.875,0.145923,0.489300
64,10,10,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.442376,0.875,0.142084,0.486487
96,20,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.139562,0.485973
144,20,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.138255,0.485537
0,10,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875,0.137112,0.485156
33,10,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.453815,0.875,0.125731,0.484849
48,10,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.438340,0.875,0.135387,0.482909
129,20,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.125220,0.482355
81,10,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.124755,0.482200
177,20,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875,0.123868,0.481905
128,20,5,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.146542,0.478727
161,20,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.115341,0.478588
113,20,5,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.114667,0.478363
80,10,10,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850,0.145096,0.478245
65,10,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.110759,0.477060
17,10,5,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.110497,0.476973
145,20,10,0.0,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.108773,0.476399
97,20,5,0.0,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.108404,0.476275
1,10,5,0.0,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.107299,0.475907
49,10,10,0.0,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875,0.107120,0.475848

,n_neighbors,n_components,min_dist,n_clusters,embedding_model,coherence,diversity,silhouette,mean_score
16,10,5,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446978,0.875000,0.145923,0.489300
64,10,10,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.442376,0.875000,0.142084,0.486487
96,20,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875000,0.139562,0.485973
144,20,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875000,0.138255,0.485537
0,10,5,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.443356,0.875000,0.137112,0.485156
33,10,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.453815,0.875000,0.125731,0.484849
48,10,10,0.0,2,paraphrase-multilingual-mpnet-base-v2,0.438340,0.875000,0.135387,0.482909
129,20,5,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875000,0.125220,0.482355
81,10,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875000,0.124755,0.482200
177,20,10,0.5,2,neuralmind/bert-base-portuguese-cased,0.446846,0.875000,0.123868,0.481905
160,20,10,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446172,0.850000,0.146559,0.480910
112,20,5,0.1,2,paraphrase-multilingual-mpnet-base-v2,0.446172,0.850000,0.146139,0.480770
32,10,5,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850000,0.147500,0.479047
128,20,5,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850000,0.146542,0.478727
161,20,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875000,0.115341,0.478588
176,20,10,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850000,0.145702,0.478447
113,20,5,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875000,0.114667,0.478363
80,10,10,0.5,2,paraphrase-multilingual-mpnet-base-v2,0.439640,0.850000,0.145096,0.478245
65,10,10,0.1,2,neuralmind/bert-base-portuguese-cased,0.445422,0.875000,0.110759,0.477060
82,10,10,0.5,3,paraphrase-multilingual-mpnet-base-v2,0.477964,0.816667,0.119915,0.471515

In [ ]:
'''Remoção de Stopwords'''
from PreProcessing.pre_processing import PreProcessing
from nltk.corpus import stopwords

pp = PreProcessing(language="pt")

custom_stopwords = [line.strip() for line in open('stopwords.txt', 'r', encoding='utf-8')]
pt_stopwords = set(stopwords.words('portuguese'))
pp.append_stopwords_list(list(pt_stopwords - set(pp.stopwords)) + custom_stopwords)

data_frame["clean_text"] = data_frame["clean_text"].apply(
    lambda t: " ".join(
        [w for w in pp.remove_stopwords(t).split() if len(w) <= 20]
    )
)

In [ ]:
import csv

nan_count = data_frame['clean_text'].isna().sum()
df = data_frame[data_frame['clean_text'].notna()].reset_index(drop=True)
print(f"{nan_count} rows with NaN in 'clean_text' were removed.")

duplicate_count = df.duplicated(subset=['clean_text']).sum()
df.drop_duplicates(subset=['clean_text'], inplace=True)
print(f"{duplicate_count} duplicate rows based on 'clean_text' were removed.")

print(f"Total documents after cleaning: {len(df)}")
docs = df['clean_text'].tolist()

print(len(df))
df.to_csv("processed_df.csv", index=False, quoting=csv.QUOTE_ALL)

0 rows with NaN in 'clean_text' were removed.
76 duplicate rows based on 'clean_text' were removed.
Total documents after cleaning: 6394
6394

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from meu_bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN

default_stopwords = []

def run_bertopic_modeling(docs, n_neighbors, n_components, min_dist, min_cluster_size, min_samples, cluster_eps,embedding_model_name="all-MiniLM-L6-v2"):
    umap_params = {
        "n_neighbors": n_neighbors, 
        "n_components": n_components, 
        "min_dist": min_dist,
        "metric":'cosine',
        "random_state":42
    }

    hdbscan_params = {
        "min_cluster_size": min_cluster_size, 
        "min_samples": min_samples,
        "prediction_data":True,
        "cluster_selection_epsilon": cluster_eps
    }

    bertopic_params = {
        'language': 'portuguese',
        #'verbose': True,
        'top_n_words': 10
    }

    
    embedding_model = SentenceTransformer(
        embedding_model_name, 
        device='cuda', 
        trust_remote_code=True
    )
    vectorizer = TfidfVectorizer(stop_words=default_stopwords,ngram_range=(1, 1))

    umap_model = UMAP(**umap_params)
    hdbscan_model = HDBSCAN(**hdbscan_params)

    model = BERTopic(
        **bertopic_params,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer,
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
    )

    topics, probs = model.fit_transform(docs)
    return model, topics, probs

/home/ester/.pyenv/versions/3.10.13/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
from IPython.display import display

def show_results(model):

    info = model.get_topic_info()
    display(info)

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)
    fig.show()

In [ ]:
import os

def save_results(model, dir):
    json_path = os.path.join(dir, "topics.json")
    model.save_json(json_path) 

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)

    barchart_path = os.path.join(dir, "barchart.html")
    fig.write_html(barchart_path) 

    model_path = os.path.join(dir, "bertopic_model")
    model.save(model_path)

    topics_info = model.get_topic_info()
    csv_path = os.path.join(dir, "topics_info.csv")
    topics_info.to_csv(csv_path, index=False)
    
    print(f"Modelo e resultados salvos no diretório '{dir}' (gráfico salvo como HTML)")

In [ ]:
for i,row in enumerate(best_mean_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps,
        embedding_model_name=row.embedding_model 
    )
    dir = f"best_mean/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=205, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4134235721696849, diversity=1.0, silhouette=0.5144956707954407, mean_score=0.6426397476550418)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5639.64it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 10:34:42,496 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=211, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4134235721696849, diversity=1.0, silhouette=0.5144956707954407, mean_score=0.6426397476550418)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4057.69it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 10:41:19,536 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=160, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-multilingual-mpnet-base-v2', coherence=0.5104410589050401, diversity=0.95, silhouette=0.3559256494045257, mean_score=0.6054555694365219)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1835.82it/s]
XLMRobertaModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 10:48:31,308 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=199, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4246120637270771, diversity=1.0, silhouette=0.2740482091903686, mean_score=0.5662200909724819)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7790.72it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 10:54:45,374 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=53, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.529239497379956, diversity=0.925, silhouette=0.2315648347139358, mean_score=0.5619347773646307)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6327.16it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 10:58:36,173 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=214, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-multilingual-mpnet-base-v2', coherence=0.478744317483287, diversity=0.9, silhouette=0.3056298196315765, mean_score=0.5614580457049545)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1265.36it/s]
XLMRobertaModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:00:22,138 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=25, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4511994245081829, diversity=1.0, silhouette=0.2243296802043914, mean_score=0.5585097015708581)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4999.83it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:04:17,364 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=123, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4580829073691868, diversity=1.0, silhouette=0.2169305831193924, mean_score=0.5583378301628598)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7141.59it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:08:10,780 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=213, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5878482033257041, diversity=0.9125, silhouette=0.1387521922588348, mean_score=0.5463667985281796)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 21672.33it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:12:04,676 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=29, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.609418942744081, diversity=0.9125, silhouette=0.1074741557240486, mean_score=0.5431310328227098)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7017.54it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:15:56,672 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=23, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6264527909788683, diversity=0.9, silhouette=0.1002554818987846, mean_score=0.5422360909592177)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8523.35it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:19:49,758 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=101, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.494320703338597, diversity=0.9, silhouette=0.2242494821548462, mean_score=0.5395233951644811)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8591.08it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:26:00,177 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=107, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.494320703338597, diversity=0.9, silhouette=0.2242494821548462, mean_score=0.5395233951644811)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4454.74it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:32:09,073 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=83, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.628609941953908, diversity=0.89, silhouette=0.099236860871315, mean_score=0.5392822676084076)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 11688.37it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:36:06,361 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=98, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=10, cluster_eps=0.1, embedding_model='paraphrase-multilingual-mpnet-base-v2', coherence=0.5284880766920439, diversity=0.8357142857142857, silhouette=0.2490271478891372, mean_score=0.5377431700984889)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1166.38it/s]
XLMRobertaModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:37:52,729 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=137, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5659922914082356, diversity=0.9166666666666666, silhouette=0.1286503672599792, mean_score=0.5371031084449606)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 9445.88it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:41:49,090 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=119, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6141078554988468, diversity=0.9125, silhouette=0.0841677635908126, mean_score=0.5369252063632198)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7818.16it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:45:41,066 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=35, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5549956529839135, diversity=0.9333333333333332, silhouette=0.1203898787498474, mean_score=0.5362396216890314)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5635.30it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:49:30,441 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=143, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4823329738436595, diversity=0.95, silhouette=0.1757541447877884, mean_score=0.536029039543816)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6319.31it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:53:25,350 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=89, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5463102181357514, diversity=0.9333333333333332, silhouette=0.1233672276139259, mean_score=0.5343369263610035)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5181.75it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 11:57:16,751 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/19' (gráfico salvo como HTML)

In [ ]:
for i,row in enumerate(best_coherence_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps,
        embedding_model_name=row.embedding_model 
    )
    dir = f"best_coherence/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=29, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.609418942744081, diversity=0.9125, silhouette=0.1074741557240486, mean_score=0.5431310328227098)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6931.99it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:38:32,324 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=23, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6264527909788683, diversity=0.9, silhouette=0.1002554818987846, mean_score=0.5422360909592177)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5293.59it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:42:31,846 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=83, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.628609941953908, diversity=0.89, silhouette=0.099236860871315, mean_score=0.5392822676084076)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5349.09it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:46:31,902 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=119, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6141078554988468, diversity=0.9125, silhouette=0.0841677635908126, mean_score=0.5369252063632198)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8297.38it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:50:32,294 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=71, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6088590705602994, diversity=0.9125, silhouette=0.0783991143107414, mean_score=0.5332527282903469)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6744.62it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:54:26,544 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=195, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6018931282214723, diversity=0.92, silhouette=0.0446088053286075, mean_score=0.52216731118336)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 9462.16it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 14:58:24,645 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=191, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6392257429585645, diversity=0.84, silhouette=-0.0092127006500959, mean_score=0.4900043474361562)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6801.61it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
for i,row in enumerate(best_diversity_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps,
        embedding_model_name=row.embedding_model 
    )
    dir = f"best_diversity/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=211, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4134235721696849, diversity=1.0, silhouette=0.5144956707954407, mean_score=0.6426397476550418)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 11486.18it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 15:42:52,413 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=205, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4134235721696849, diversity=1.0, silhouette=0.5144956707954407, mean_score=0.6426397476550418)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7879.04it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 15:47:02,755 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=160, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-multilingual-mpnet-base-v2', coherence=0.5104410589050401, diversity=0.95, silhouette=0.3559256494045257, mean_score=0.6054555694365219)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1299.16it/s]
XLMRobertaModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 15:48:53,208 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=199, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4246120637270771, diversity=1.0, silhouette=0.2740482091903686, mean_score=0.5662200909724819)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6446.65it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 15:53:01,890 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=25, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4511994245081829, diversity=1.0, silhouette=0.2243296802043914, mean_score=0.5585097015708581)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5324.04it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 15:57:00,108 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=123, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4580829073691868, diversity=1.0, silhouette=0.2169305831193924, mean_score=0.5583378301628598)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7373.57it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:00:58,339 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=35, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5549956529839135, diversity=0.9333333333333332, silhouette=0.1203898787498474, mean_score=0.5362396216890314)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8094.44it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:04:50,512 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=143, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4823329738436595, diversity=0.95, silhouette=0.1757541447877884, mean_score=0.536029039543816)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7811.79it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:08:46,030 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=89, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5463102181357514, diversity=0.9333333333333332, silhouette=0.1233672276139259, mean_score=0.5343369263610035)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6113.83it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:12:41,909 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=91, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4583321384668378, diversity=0.94, silhouette=0.2023081928491592, mean_score=0.5335467771053323)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8599.40it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:16:32,363 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=155, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4783928868309069, diversity=0.925, silhouette=0.1897852271795272, mean_score=0.5310593713368114)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17711.76it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:20:27,293 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=149, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.4783928868309069, diversity=0.925, silhouette=0.1897852271795272, mean_score=0.5310593713368114)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8114.90it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:24:21,977 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=31, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5350760329921443, diversity=0.95, silhouette=0.1071079671382904, mean_score=0.5307280000434783)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7921.29it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:28:11,854 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=207, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5109890506421717, diversity=0.93, silhouette=0.1383563578128814, mean_score=0.5264484694850178)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7143.12it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:32:05,465 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=43, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5661712419474718, diversity=0.95, silhouette=0.0454274378716945, mean_score=0.5205328932730554)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6828.38it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:35:58,670 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=37, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5408988766658013, diversity=0.95, silhouette=0.0534066259860992, mean_score=0.5147685008839669)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10247.09it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:39:52,930 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=175, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5348242553948634, diversity=0.925, silhouette=0.0584658868610858, mean_score=0.5060967140853164)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5882.37it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:43:47,982 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=193, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5476351749403342, diversity=0.925, silhouette=0.0272084549069404, mean_score=0.4999478766157582)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5134.20it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-28 16:47:40,321 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=27, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5089610334753328, diversity=0.9333333333333332, silhouette=0.0556647405028343, mean_score=0.4993197024371668)

No sentence-transformers model found with name neuralmind/bert-base-portuguese-cased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 16685.99it/s]
BertModel LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
for i,row in enumerate(best_silhouette_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps,
        embedding_model_name=row.embedding_model 
    )
    dir = f"best_silhouette/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=323, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5417229015002559, diversity=0.975, silhouette=0.8252971172332764, mean_score=0.7806733395778441)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 656.98it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:54:03,735 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=419, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.6027604325277752, diversity=0.875, silhouette=0.7019891738891602, mean_score=0.7265832021389785)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 963.36it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:55:15,992 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=107, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5135843600776806, diversity=0.95, silhouette=0.6927226185798645, mean_score=0.7187689928858484)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 938.47it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:56:20,994 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=83, n_neighbors=10, n_components=5, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5135843600776806, diversity=0.95, silhouette=0.6927226185798645, mean_score=0.7187689928858484)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 566.87it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:57:32,089 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=416, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='all-MiniLM-L6-v2', coherence=0.4950726227697918, diversity=0.8875, silhouette=0.7530953884124756, mean_score=0.7118893370607559)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 954.85it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:58:41,702 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=428, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='all-MiniLM-L6-v2', coherence=0.4950726227697918, diversity=0.8875, silhouette=0.7530953884124756, mean_score=0.7118893370607559)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1080.20it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 13:59:48,604 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=404, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='all-MiniLM-L6-v2', coherence=0.5314474584635576, diversity=0.86, silhouette=0.7055774927139282, mean_score=0.699008317059162)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1209.45it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:00:57,185 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=250, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4463097761162006, diversity=0.85, silhouette=0.7565691471099854, mean_score=0.6842929744087286)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1059.38it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:01:59,573 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=246, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4463097761162005, diversity=0.85, silhouette=0.7509785294532776, mean_score=0.682429435189826)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 927.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:03:03,929 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=242, n_neighbors=20, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4164933471002093, diversity=0.875, silhouette=0.7517907023429871, mean_score=0.681094683147732)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1104.66it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:04:10,984 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=202, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4477910613446251, diversity=0.8, silhouette=0.7853795886039734, mean_score=0.6777235499828662)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1064.39it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:05:14,175 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=139, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='neuralmind/bert-base-portuguese-cased', coherence=0.5914637221861143, diversity=0.7277777777777777, silhouette=0.7043157815933228, mean_score=0.6745190938524049)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1154.55it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:06:15,647 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=430, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4240691276621192, diversity=0.8166666666666667, silhouette=0.7609965205192566, mean_score=0.6672441049493475)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1088.04it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:07:22,934 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=190, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.456429120311605, diversity=0.7625, silhouette=0.7682042717933655, mean_score=0.6623777973683235)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 916.74it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:11:59,006 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=330, n_neighbors=20, n_components=10, min_dist=0.0, min_cluster_size=50, min_samples=10, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4342427883006746, diversity=0.7675, silhouette=0.762013852596283, mean_score=0.6545855469656525)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 991.12it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:12:54,986 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=418, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.46038917872543, diversity=0.75, silhouette=0.7212034463882446, mean_score=0.6438642083712248)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1517.20it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:13:38,041 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=406, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.46038917872543, diversity=0.75, silhouette=0.7212034463882446, mean_score=0.6438642083712248)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1642.22it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:14:20,600 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=2, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4585807107236507, diversity=0.7304347826086957, silhouette=0.7101621627807617, mean_score=0.6330592187043694)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1729.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:14:59,454 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=33, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.4436303703331396, diversity=0.725, silhouette=0.7220777273178101, mean_score=0.6302360325503166)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1709.86it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:15:39,749 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=374, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.4736255297933349, diversity=0.71, silhouette=0.6994773149490356, mean_score=0.6277009482474568)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1427.90it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-26 14:16:22,306 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/19' (gráfico salvo como HTML)